name: "Gosec Security Checker"
description: "Runs the gosec security checker"
author: 'step-security'

inputs:
  args:
    description: "Arguments for gosec"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "ghcr.io/step-security/securego-gosec:v2.28.0@sha256:8f9014764933fca2c3fc198f7740c18da2c0932d69f4e921bc905974e1f7c228" # v2.28.0
  args:
    - ${{ inputs.args }}

branding:
  icon: "shield"
  color: "blue"
