name: "Gosec Security Checker"
description: "Runs the gosec security checker"
author: 'step-security'

inputs:
  args:
    description: "Arguments for gosec"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://ghcr.io/step-security/securego-gosec:v2.29.0@sha256:84e2b8e6155ac898b14fcdf0ee0a23c9d7c08d09af9ff90e8f7663a939a3e1a7" # v2.29.0
  args:
    - ${{ inputs.args }}

branding:
  icon: "shield"
  color: "blue"
